import FreeCAD as App
import Part
import math

# پارامترهای اصلی
cylinder_diameter = 15.0  # mm (1.5 cm)
cylinder_radius = cylinder_diameter / 2.0
cylinder_length = 80.0  # mm (8 cm)
module = 1.0  # ماژول دنده‌ها (mm)
pressure_angle = 20.0  # زاویه فشار (درجه)

# محاسبات دنده‌ها
pitch = module * math.pi  # گام دنده‌ها (mm)
num_teeth = int(cylinder_length / pitch)  # تعداد دنده‌ها در طول استوانه

# ایجاد استوانه اصلی
cylinder = Part.makeCylinder(cylinder_radius, cylinder_length)

# ایجاد یک جعبه برای برش ربع استوانه
cut_box = Part.makeBox(cylinder_radius, cylinder_radius, cylinder_length)

# جابجایی جعبه به لبه استوانه و چرخش 45 درجه برای برش یک ربع
cut_box.translate(App.Vector(0, -cylinder_radius, 0))
cut_box.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 45)

# برش ربع استوانه
quarter_cylinder = cylinder.cut(cut_box)

# ایجاد دنده‌های شانه‌ای روی سطح صاف
teeth = []
for i in range(num_teeth):
    # مختصات هر دنده
    x_start = i * pitch
    tooth = Part.makeBox(
        pitch,  # طول دنده
        cylinder_radius * 0.5,  # عمق دنده (نصف شعاع)
        module * 2.25,  # ارتفاع دنده (طبق استاندارد ماژول)
        App.Vector(x_start, -cylinder_radius, 0),  # موقعیت شروع
    )
    teeth.append(tooth)

# ترکیب همه دنده‌ها
rack_teeth = Part.makeCompound(teeth)

# ادغام دنده‌ها با ربع استوانه
final_part = quarter_cylinder.fuse(rack_teeth)

# نمایش قطعه در FreeCAD
Part.show(final_part, "Cylindrical_Rack_Gear")
