import FreeCAD
import Part
from FreeCAD import Base

# ایجاد سند جدید
doc = FreeCAD.newDocument("OffsetCutCylinder")

# پارامترهای استوانه
diameter = 15.0  # قطر به میلی‌متر (1.5 سانت)
radius = diameter / 2
length = 80.0    # طول به میلی‌متر (8 سانت)
additional_offset = 3.0  # 3 میلی‌متر آن‌سوتر از نیمه
total_cut_offset = radius + additional_offset  # مجموعاً 10.5mm از مرکز

# ایجاد استوانه اصلی
cylinder = Part.makeCylinder(radius, length, Base.Vector(0,0,0), Base.Vector(0,0,1))

# ایجاد جعبه برش با دقت بالا
cut_thickness = 0.1  # ضخامت برش 0.1mm برای دقت
cut_height = length * 1.2  # ارتفاع بیشتر از طول استوانه
cut_width = diameter * 2   # عرض کافی برای پوشش
cut_box = Part.makeBox(cut_thickness, cut_width, cut_height,
                     Base.Vector(total_cut_offset - cut_thickness, -cut_width/2, -cut_height/2))

# انجام برش
cut_cylinder = cylinder.cut(cut_box)

# اضافه کردن به سند
cyl_obj = doc.addObject("Part::Feature", "3mmOffsetCutCylinder")
cyl_obj.Shape = cut_cylinder

# تنظیم نمایش
FreeCADGui.ActiveDocument.ActiveView.viewAxometric()
FreeCADGui.SendMsgToActiveView("ViewFit")
doc.recompute()

print(f"برش از {total_cut_offset}mm از مرکز انجام شد (نیمه: {radius}mm + اضافه: {additional_offset}mm)")
