import FreeCAD, Part, math
from FreeCAD import Base

doc = FreeCAD.ActiveDocument

# پارامترهای چرخ دنده شانه‌ای
MODULE = 1.0  # استاندارد ISO
LENGTH = 60.0 # 6 cm
WIDTH = 12.0  # 1.2 cm
PRESSURE_ANGLE = math.radians(20) # 20 درجه

# تابع ساخت چرخ دنده شانه‌ای
def create_rack_gear(length, width, module, pressure_angle):
    rack = doc.addObject("Part::Feature", "RackGear")
    
    # محاسبات دندانه‌ها
    tooth_width = math.pi * module / 2
    num_teeth = int(length / (math.pi * module))
    
    points = []
    for i in range(num_teeth + 1):
        x = i * math.pi * module
        # پروفیل دندانه (مثلثی ساده)
        points.append(Base.Vector(x, 0, 0))
        points.append(Base.Vector(x + tooth_width, 0, module))
        points.append(Base.Vector(x + math.pi * module, 0, 0))
    
    # ایجاد شکل
    wire = Part.makePolygon(points)
    face = Part.Face(Part.Wire(wire))
    rack.Shape = face.extrude(Base.Vector(0, width, 0))
    return rack

# ساخت قطعه اصلی (همانند قبل)
cylinder = doc.addObject("Part::Cylinder", "Cylinder")
cylinder.Height = 80.0
cylinder.Radius = 8.0

cut_tool = doc.addObject("Part::Box", "CutTool")
cut_tool.Length = 50.0
cut_tool.Width = 50.0
cut_tool.Height = 100.0
cut_tool.Placement = Base.Placement(Base.Vector(5,-25,-10), Base.Rotation())

cut_result = doc.addObject("Part::Cut", "CutResult")
cut_result.Base = cylinder
cut_result.Tool = cut_tool

# ساخت چرخ دنده شانه‌ای
rack_gear = create_rack_gear(LENGTH, WIDTH, MODULE, PRESSURE_ANGLE)
rack_gear.Placement = Base.Placement(
    Base.Vector(5, -WIDTH/2, 40),  # تراز با سطح برش‌خورده
    Base.Rotation(90, 0, 0),        # چرخش برای قرارگیری روی سطح
    Base.Vector(0, 0, 0)
)

# ادغام نهایی
final_part = doc.addObject("Part::Fuse", "FinalPart")
final_part.Base = cut_result
final_part.Tool = rack_gear

# مخفی کردن اشیاء موقت
cylinder.ViewObject.Visibility = False
cut_tool.ViewObject.Visibility = False
rack_gear.ViewObject.Visibility = False

doc.recompute()
FreeCADGui.ActiveDocument.ActiveView.fitAll()
