import FreeCAD
import FreeCADGui
import Part
import math

def create_rack_gear():
    doc = FreeCAD.newDocument("RackGear")
    
    # پارامترهای طراحی
    length = 80.0    # طول 80mm (8cm)
    width = 12.0     # عرض 12mm (1.2cm)
    teeth = 25       # تعداد دنده‌ها
    pressure_angle = 20.0  # زاویه فشار
    module = width / teeth
    
    # 1. ایجاد پروفیل دنده شانه ای
    rack_profile = []
    tooth_space = math.pi * module
    tooth_height = 2.25 * module
    
    for i in range(teeth):
        x = i * tooth_space
        # اضافه کردن نقاط برای یک دنده
        rack_profile.append(FreeCAD.Vector(x, -tooth_height/2, 0))
        rack_profile.append(FreeCAD.Vector(x, tooth_height/2, 0))
        rack_profile.append(FreeCAD.Vector(x + tooth_space/2, tooth_height/2, 0))
        rack_profile.append(FreeCAD.Vector(x + tooth_space/2, -tooth_height/2, 0))
    
    # بستن پروفیل
    rack_profile.append(rack_profile[0])
    
    # ایجاد شکل سیمی
    wire = Part.makePolygon(rack_profile)
    face = Part.Face(wire)
    rack = face.extrude(FreeCAD.Vector(0, 0, length))
    
    # 2. ایجاد استوانه پایه
    cylinder = Part.makeCylinder(width/2, length)
    cylinder.translate(FreeCAD.Vector(0, 0, 0))
    
    # 3. ترکیب قطعات
    final_rack = rack.fuse(cylinder)
    
    # اضافه کردن به سند
    obj = doc.addObject("Part::Feature", "RackGear")
    obj.Shape = final_rack
    obj.ViewObject.ShapeColor = (0.8, 0.2, 0.0)
    
    doc.recompute()
    FreeCADGui.SendMsgToActiveView("ViewFit")

create_rack_gear()
