import FreeCAD
import Part
import math

# پارامترهای چرخدنده
module = 1.5  # اندازه ماژول (فاصله بین دندانه‌ها) - متناسب با قطر 15mm
num_teeth = 10  # تعداد دندانه‌ها
gear_length = 80.0  # طول چرخدنده (mm)
pressure_angle = 20  # زاویه فشار (درجه)

# محاسبات اولیه
pitch_radius = (module * num_teeth) / 2
base_radius = pitch_radius * math.cos(math.radians(pressure_angle))

# تابع ایجاد پروفیل یک دندانه (در صفحه XZ)
def create_tooth_profile():
    points = []
    for i in range(21):
        t = i / 20.0 * (math.pi / 2)
        x = base_radius * (math.cos(t) + t * math.sin(t))
        z = base_radius * (math.sin(t) - t * math.cos(t))
        points.append(FreeCAD.Vector(x, 0, z))  # توجه: Y=0 (موازی محور Z)
    
    # ایجاد سیم (Wire) از نقاط
    wire = Part.makePolygon(points)
    return wire

# ایجاد یک دندانه و اکسترود در جهت Y (عرض چرخدنده)
tooth_profile = create_tooth_profile()
tooth_face = Part.Face(tooth_profile)
tooth_solid = tooth_face.extrude(FreeCAD.Vector(0, gear_length, 0))  # اکسترود در جهت Y

# کپی و چرخش دندانه‌ها حول محور Z
gear = None
for i in range(num_teeth):
    angle = 360.0 / num_teeth * i
    rotation = FreeCAD.Rotation(FreeCAD.Vector(0, 0, 1), angle)
    placement = FreeCAD.Placement(FreeCAD.Vector(0, 0, 0), rotation)
    
    new_tooth = tooth_solid.copy()
    new_tooth.Placement = placement
    
    if gear is None:
        gear = new_tooth
    else:
        gear = gear.fuse(new_tooth)

# ایجاد هسته مرکزی (استوانه مرکزی)
core_cylinder = Part.makeCylinder(pitch_radius - module, gear_length, FreeCAD.Vector(0, 0, 0), FreeCAD.Vector(0, 1, 0))
gear = gear.fuse(core_cylinder)

# نمایش نتیجه
Part.show(gear)
FreeCAD.ActiveDocument.recompute()
