import FreeCAD
import Part
import math

def create_spur_gear(module=1.0, teeth=20, thickness=12.0, pressure_angle=20.0):
    """
    تابع ایجاد چرخ دنده استاندارد با پارامترهای:
    module: مدول دندانه (مطابق با چرخ دنده شانه‌ای)
    teeth: تعداد دندانه‌ها
    thickness: ضخامت چرخ دنده
    pressure_angle: زاویه فشار (درجه)
    """
    # تبدیل زاویه به رادیان
    pressure_angle = math.radians(pressure_angle)
    
    # محاسبات پارامترهای چرخ دنده
    pitch_diameter = module * teeth
    addendum = module
    dedendum = 1.25 * module
    outer_diameter = pitch_diameter + 2 * addendum
    base_diameter = pitch_diameter * math.cos(pressure_angle)
    
    # ایجاد نقاط پروفیل دندانه
    points = []
    for i in range(teeth + 1):
        angle = 2 * math.pi * i / teeth
        # نقاط پروفیل اینولوت
        x = base_diameter/2 * (math.cos(angle) + angle * math.sin(angle))
        y = base_diameter/2 * (math.sin(angle) - angle * math.cos(angle))
        points.append(FreeCAD.Vector(x, y, 0))
    
    # ایجاد شکل دندانه‌ها
    wire = Part.makePolygon(points)
    face = Part.Face(Part.Wire(wire))
    gear = face.revolve(FreeCAD.Vector(0,0,0), FreeCAD.Vector(0,0,1), 360)
    
    # اکسترود به ضخامت مورد نظر
    extruded_gear = gear.extrude(FreeCAD.Vector(0,0,thickness))
    
    # ایجاد شیء در سند
    doc = FreeCAD.ActiveDocument or FreeCAD.newDocument("GearAssembly")
    gear_obj = doc.addObject("Part::Feature", "SpurGear")
    gear_obj.Shape = extruded_gear
    
    # تنظیمات نمایش
    gear_obj.ViewObject.ShapeColor = (0.33, 0.33, 0.67)  # رنگ آبی-خاکستری
    doc.recompute()
    
    return gear_obj

# ایجاد چرخ دنده با پارامترهای استاندارد
spur_gear = create_spur_gear(
    module=1.0,      # مطابق با چرخ دنده شانه‌ای
    teeth=20,       # تعداد دندانه‌های مناسب
    thickness=12.0, # هماندازه با عرض چرخ دنده شانه‌ای
    pressure_angle=20.0  # زاویه استاندارد
)
